export const SET_LOADING = 'SET_LOADING';

export const GET_MY_BALANCE_LOADING = 'GET_MY_BALANCE_LOADING';
export const BUY_UNOTOKEN_LOADING = 'BUY_UNOTOKEN_LOADING';
export const SWAP_TOKEN_LOADING = 'SWAP_TOKEN_LOADING';
